// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-1l08y2UGSFkVg5tO4_xx80R4uE2iZk',
    appId: '1:212940960827:web:609e0da3e4472dbb36581e',
    messagingSenderId: '212940960827',
    projectId: 'onbooks-3ef7f',
    authDomain: 'onbooks-3ef7f.firebaseapp.com',
    storageBucket: 'onbooks-3ef7f.appspot.com',
    measurementId: 'G-87KYC1DLP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBrDDK0CNlwD-kz28XtLWITOrbvoU4Dc',
    appId: '1:212940960827:android:fdd27997dc51375236581e',
    messagingSenderId: '212940960827',
    projectId: 'onbooks-3ef7f',
    storageBucket: 'onbooks-3ef7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr5wmY44VLnWs7MkBMZjSINKXXFsL4Vwc',
    appId: '1:212940960827:ios:4c28ceed3cacefd936581e',
    messagingSenderId: '212940960827',
    projectId: 'onbooks-3ef7f',
    storageBucket: 'onbooks-3ef7f.appspot.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr5wmY44VLnWs7MkBMZjSINKXXFsL4Vwc',
    appId: '1:212940960827:ios:4c28ceed3cacefd936581e',
    messagingSenderId: '212940960827',
    projectId: 'onbooks-3ef7f',
    storageBucket: 'onbooks-3ef7f.appspot.com',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-1l08y2UGSFkVg5tO4_xx80R4uE2iZk',
    appId: '1:212940960827:web:dea88e0bd507091c36581e',
    messagingSenderId: '212940960827',
    projectId: 'onbooks-3ef7f',
    authDomain: 'onbooks-3ef7f.firebaseapp.com',
    storageBucket: 'onbooks-3ef7f.appspot.com',
    measurementId: 'G-F94ZHM506X',
  );

}